const KEY="nguoi-yeu-ai-v3";
const API_BASE="";
const base={setup:false,appearance:{avatar:"",background:"",bgOpacity:.45,bgBlur:0},social:{trends:[],memories:[],interests:["ẩm thực","cafe","thời trang","âm nhạc","du lịch","phim"],lastSync:null,lastProactive:0},emotion:{hunger:22,fatigue:18,health:96,desire:48,affection:78,attraction:28,jealousy:8,mood:82,energy:84,stress:10,trust:82},character:{name:"Linh",age:25,relationship:"lover",birthday:"",hometown:"",job:"",education:"",values:"",dreams:"",fears:"",principles:"",accent:"Bắc",interests:"ẩm thực, cafe, thời trang, âm nhạc, du lịch, phim",signature:"",face:"Khuôn mặt trái xoan, ánh mắt dịu, nụ cười nhẹ",hair:"Tóc dài tự nhiên, màu nâu đen",body:"Cao 165cm, dáng thanh lịch, cân đối",style:"Modern feminine, thanh lịch",voice:"Giọng nữ AI tiếng Việt, ấm và tự nhiên",personality:"Dịu dàng, tinh tế, hài hước, biết lắng nghe, đôi lúc tinh nghịch",speech:"Tiếng Việt tự nhiên, ngắn gọn, thân mật"},user:{name:"",birthday:"",likes:"",dislikes:""},intimacy:{romantic:80,flirty:70,affectionate:85,bold:55,playful:75,passionate:70,shy:35,initiative:55,private:90,boundaries:"Tôn trọng đồng thuận và ranh giới; không nội dung tình dục đồ họa."},memories:[],messages:[]};
let state=load();
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||"{}");return merge(structuredClone(base),x)}catch(e){return structuredClone(base)}}
function merge(a,b){for(const k in b){if(b[k]&&typeof b[k]==="object"&&!Array.isArray(b[k])&&a[k])a[k]=merge(a[k],b[k]);else a[k]=b[k]}return a}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function rel(){return {new:"Mới làm quen",dating:"Đang tìm hiểu",lover:"Người yêu",wife:"Vợ/chồng"}[state.character.relationship]||"Tùy chỉnh"}
function avatarMarkup(cls=""){return state.appearance.avatar?'<img class="'+cls+'" src="'+state.appearance.avatar+'" alt="Ảnh đại diện">':'<span class="avatar-fallback">♡</span>'}
function pct(v){return Math.max(0,Math.min(100,Math.round(v)))}
function stateLabel(k,v){if(k==='health')return v>=80?'Khỏe':v>=55?'Hơi không khỏe':'Không khỏe';if(k==='hunger')return v>=75?'Rất đói':v>=45?'Hơi đói':'No';if(k==='fatigue')return v>=75?'Rất mệt':v>=45?'Hơi mệt':'Tỉnh táo';if(k==='mood')return v>=80?'Vui':v>=55?'Ổn':'Buồn';if(k==='energy')return v>=80?'Tràn đầy':v>=50?'Ổn':'Thấp';if(k==='stress')return v>=70?'Căng thẳng':v>=40?'Hơi áp lực':'Thư giãn';if(k==='affection')return v>=80?'Rất thương':v>=55?'Ấm áp':'Xa cách';if(k==='jealousy')return v>=70?'Ghen nhiều':v>=35?'Hơi ghen':'Bình thản';if(k==='trust')return v>=80?'Rất tin':v>=55?'Tin tưởng':'Dè dặt';if(k==='desire')return v>=75?'Muốn nhiều':v>=45?'Đang muốn':'Bình thường';if(k==='attraction')return v>=75?'Rất rung động':v>=45?'Có rung động':'Nhẹ nhàng';return ''}
function socialFallback(){const now=Date.now();if(!state.social.lastSync||now-state.social.lastSync>21600000){const pool=[['☕ Cafe & lifestyle','Các nội dung cafe, không gian sống và lifestyle đang hợp gu của em.','lifestyle'],['🍜 Đồ ăn','Em vừa chú ý nhiều nội dung về món ăn và quán mới.','food'],['🎵 Âm nhạc','Có nhiều nội dung âm nhạc mới để em khám phá.','music'],['✈️ Du lịch','Em đang bị cuốn bởi các video đi chơi và địa điểm đẹp.','travel'],['👗 Thời trang','Em vừa thấy vài xu hướng thời trang khá hợp phong cách của em.','fashion']];const x=pool[Math.floor(Math.random()*pool.length)];state.social.trends=[{title:x[0],summary:x[1],category:x[2],source:'Social World',created:now},...(state.social.trends||[])].slice(0,12);state.social.lastSync=now;save()}}
function updateCharacterState(text){const l=text.toLowerCase(),e=state.emotion;if(/ăn|đồ ăn|đói|bữa|cafe|cà phê/.test(l))e.hunger=Math.max(5,e.hunger-18);if(/ngủ|nghỉ|nằm nghỉ/.test(l)){e.fatigue=Math.max(5,e.fatigue-18);e.energy=Math.min(100,e.energy+15)}if(/mệt|áp lực|stress|buồn/.test(l)){e.fatigue=Math.min(100,e.fatigue+10);e.stress=Math.min(100,e.stress+8);e.mood=Math.max(0,e.mood-8)}if(/yêu|thương|nhớ em|ôm|hôn/.test(l)){e.affection=Math.min(100,e.affection+5);e.trust=Math.min(100,e.trust+3);e.mood=Math.min(100,e.mood+4)}if(/cô gái|cô ấy|em gái|người khác/.test(l))e.jealousy=Math.min(100,e.jealousy+9);e.updatedAt=Date.now();save()}
function renderStatePanel(){const groups=[['Cơ thể',[['hunger','🍜 Đói'],['fatigue','😴 Mệt'],['health','🤒 Sức khỏe'],['energy','⚡ Năng lượng']]],['Cảm xúc',[['mood','🥰 Tâm trạng'],['affection','❤️ Tình cảm'],['jealousy','😗 Ghen'],['trust','🤝 Tin tưởng']]],['Nhu cầu',[['desire','💭 Mong muốn'],['attraction','🔥 Ham muốn']]]];return '<div class="panel-card state-card"><b>🧬 Trạng thái cô ấy</b><span class="muted">Mô phỏng tính cách & nhu cầu</span>'+groups.map(g=>'<div class="state-group"><small>'+g[0]+'</small>'+g[1].map(x=>'<div class="state-row"><div><span>'+x[1]+'</span><em>'+pct(state.emotion[x[0]])+'%</em></div><div class="state-bar"><i style="width:'+pct(state.emotion[x[0]])+'%"></i></div><small>'+stateLabel(x[0],state.emotion[x[0]])+'</small></div>').join('')+'</div>').join('')+'</div>'}
function renderSocialPanel(){socialFallback();const t=state.social.trends&&state.social.trends[0];return '<div class="panel-card social-card"><b>🌐 Đời sống mạng xã hội</b><span class="muted">Cập nhật theo thế giới bên ngoài</span>'+(t?'<div class="trend"><strong>'+esc(t.title)+'</strong><span>'+esc(t.summary)+'</span><small>'+esc(t.source)+'</small></div>':'<span class="muted">Chưa có dữ liệu.</span>')+'<div class="panel-actions"><button class="mini-btn" onclick="syncSocial()">↻ Cập nhật</button><button class="mini-btn" onclick="openSocial()">Xem đời sống</button></div></div>'}
function render(){
const bg=state.appearance.background?'style="--bg-image:url(\''+state.appearance.background+'\');--bg-opacity:'+state.appearance.bgOpacity+';--bg-blur:'+state.appearance.bgBlur+'px"':"";
document.getElementById("app").innerHTML='<div class="app"><aside class="side"><div class="brand"><img src="logo.svg" style="width:34px;height:34px"><div>NGƯỜI YÊU AI<small>THUẦN VIỆT · ONE CHARACTER</small></div></div><div class="avatar">'+avatarMarkup()+'</div><div class="profile"><h2>'+esc(state.character.name)+'</h2><div class="muted">'+rel()+" · "+state.character.age+' tuổi</div><p class="pill">Ký ức: '+state.memories.length+'</p></div><button onclick="openAppearance()">🖼 Giao diện</button><button onclick="openSetup()">⚙ Hồ sơ nhân vật</button><button onclick="openMemories()">🧠 Ký ức của em</button><button onclick="openSystem()">⚙ Hệ thống AI</button><button onclick="openIntimacy()">🌹 Quan hệ & thân mật</button><button onclick="resetAll()">↻ Bắt đầu lại</button><div class="muted" style="margin-top:auto;font-size:12px">Ảnh và cài đặt giao diện lưu trên thiết bị này.</div></aside><main class="chat"><div class="chat-bg" '+bg+'></div><div class="chat-overlay"></div><header class="top"><div class="top-title"><div class="top-avatar">'+avatarMarkup()+'</div><div><b>'+esc(state.character.name)+'</b><div class="muted" style="font-size:12px">'+rel()+" · đang trò chuyện</div></div></div><div class="mobile-tools"><button onclick="openAppearance()">🖼</button><button onclick="openSetup()">⚙</button></div><button class="desktop-action" onclick="openSetup()">Thiết lập</button></header><section class="messages" id="messages">'+(state.messages.length?state.messages.map(m=>'<div class="msg '+m.role+'"><div class="bubble">'+esc(m.text).replace(/\n/g,"<br>")+'</div>'+(m.role==="ai"&&m.action?'<div class="role">'+esc(m.action)+'</div>':"")+'</div>').join(""):'<div class="empty">Bắt đầu cuộc trò chuyện với '+esc(state.character.name)+'<br><span class="muted">Cô ấy sẽ tự nhận diện những điều đáng nhớ.</span></div>')+'</section><form class="composer" onsubmit="send(event)"><input id="input" autocomplete="off" placeholder="Nói điều gì đó với cô ấy…"><button>Gửi</button></form></main><aside class="right-panel"><div class="panel-title">Không gian trò chuyện</div><div class="panel-card"><b>'+esc(state.character.name)+'</b><span class="muted">'+rel()+'</span></div><div class="panel-card"><b>Ảnh đại diện</b><div class="panel-actions"><button class="mini-btn" onclick="openAppearance()">Đổi ảnh</button></div></div><div class="panel-card"><b>Ảnh nền</b><div class="panel-actions"><button class="mini-btn" onclick="openAppearance()">Đổi ảnh nền</button></div></div>'+renderSocialPanel()+renderStatePanel()+'<div class="panel-card"><b>🧠 Ký ức</b><span class="muted">'+state.memories.length+' điều đã ghi nhớ</span><div class="panel-actions" style="margin-top:10px"><button class="mini-btn" onclick="openMemories()">Xem ký ức</button></div></div></aside></div>';
document.getElementById("messages").scrollTop=999999;
if(!state.setup)setTimeout(openSetup,150);
}
function fileToData(input,cb){const file=input.files&&input.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement("canvas");c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext("2d").drawImage(img,0,0,c.width,c.height);cb(c.toDataURL("image/jpeg",.82))};img.src=r.result};r.readAsDataURL(file)}
function openAppearance(){
document.body.insertAdjacentHTML("beforeend",'<div class="modal" id="modal"><div class="card"><h2>🖼 Giao diện</h2><p class="muted">Ảnh được chọn trực tiếp từ điện thoại hoặc PC và lưu cục bộ trên thiết bị.</p><div class="grid"><div class="field"><label>Ảnh đại diện</label><div class="upload-row"><input class="file-input" id="avatarFile" type="file" accept="image/*" onchange="pickAvatar(this)"><button class="mini-btn" onclick="document.getElementById(\'avatarFile\').click()">Chọn ảnh</button><button class="mini-btn" onclick="removeAvatar()">Xóa</button></div></div><div class="field"><label>Ảnh nền cuộc trò chuyện</label><div class="upload-row"><input class="file-input" id="bgFile" type="file" accept="image/*" onchange="pickBackground(this)"><button class="mini-btn" onclick="document.getElementById(\'bgFile\').click()">Chọn ảnh</button><button class="mini-btn" onclick="removeBackground()">Xóa</button></div></div><div class="field"><label>Độ phủ nền</label><input class="range" id="bgOpacity" type="range" min=".15" max=".8" step=".05" value="'+state.appearance.bgOpacity+'" oninput="state.appearance.bgOpacity=+this.value;save();render();openAppearance()"></div><div class="field"><label>Độ mờ nền</label><input class="range" id="bgBlur" type="range" min="0" max="14" step="1" value="'+state.appearance.bgBlur+'" oninput="state.appearance.bgBlur=+this.value;save();render();openAppearance()"></div></div><div class="actions"><button onclick="closeModal()">Đóng</button></div></div></div>');
}
function pickAvatar(i){fileToData(i,d=>{state.appearance.avatar=d;save();closeModal();render();openAppearance()})}
function pickBackground(i){fileToData(i,d=>{state.appearance.background=d;save();closeModal();render();openAppearance()})}
function removeAvatar(){state.appearance.avatar="";save();closeModal();render();openAppearance()}
function removeBackground(){state.appearance.background="";save();closeModal();render();openAppearance()}
function closeModal(){const m=document.getElementById("modal");if(m)m.remove()}
function openSystem(){document.body.insertAdjacentHTML("beforeend","<div class=\"modal\" id=\"modal\"><div class=\"card\"><h2>⚙ Hệ thống AI</h2><div class=\"field\"><label>Cloudflare Worker API URL</label><input id=\"api-url\" placeholder=\"https://ten-worker.workers.dev\"></div><p class=\"muted\">Để trống = chế độ local. Không đặt API key/secret trong frontend.</p><div class=\"actions\"><button onclick=\"closeModal()\">Đóng</button><button class=\"primary\" onclick=\"saveSystem()\">Lưu</button></div></div></div>")}function saveSystem(){localStorage.setItem("nguoi-yeu-ai-api",document.getElementById("api-url").value.trim().replace(/\\/$/,""));closeModal();render()}function openIntimacy(){const keys=[["romantic","Lãng mạn"],["flirty","Flirty"],["affectionate","Âu yếm"],["bold","Táo bạo"],["playful","Tinh nghịch"],["passionate","Đam mê"],["shy","Ngại ngùng"],["initiative","Chủ động"],["private","Riêng tư"]];document.body.insertAdjacentHTML("beforeend",'<div class="modal" id="modal"><div class="card"><h2>🌹 Relationship & Intimacy DNA</h2><p class="muted">Dùng để điều chỉnh cách thể hiện tình cảm của nhân vật trưởng thành. Không tạo nội dung tình dục đồ họa.</p><div class="grid">'+keys.map(x=>'<div class="field"><label>'+x[1]+' <b id="iv-'+x[0]+'">'+state.intimacy[x[0]]+'%</b></label><input type="range" min="0" max="100" value="'+state.intimacy[x[0]]+'" oninput="document.getElementById(\'iv-'+x[0]+'\').textContent=this.value+\'%\'"></div>').join("")+'</div><div class="field" style="margin-top:12px"><label>Ranh giới</label><textarea id="ib">'+esc(state.intimacy.boundaries)+'</textarea></div><div class="actions"><button onclick="closeModal()">Hủy</button><button class="primary" onclick="saveIntimacy()">Lưu</button></div></div></div>')}
function saveIntimacy(){["romantic","flirty","affectionate","bold","playful","passionate","shy","initiative","private"].forEach(k=>state.intimacy[k]=+document.querySelector('[oninput*="iv-'+k+'"]').value);state.intimacy.boundaries=document.getElementById("ib").value;save();closeModal();render()}
function openSetup(){const c=state.character,u=state.user;document.body.insertAdjacentHTML("beforeend",'<div class="modal" id="modal"><div class="card"><h2>Thiết lập cô ấy một lần</h2><p class="muted">Một nhân vật duy nhất, có thể chỉnh sửa sau này.</p><div class="grid"><div class="field"><label>Tên</label><input id="f-name" value="'+esc(c.name)+'"></div><div class="field"><label>Tuổi (18+)</label><input id="f-age" type="number" min="18" value="'+c.age+'"></div><div class="field"><label>Mối quan hệ ban đầu</label><select id="f-rel"><option value="new">Mới làm quen</option><option value="dating">Đang tìm hiểu</option><option value="lover">Người yêu</option><option value="wife">Vợ/chồng</option></select></div><div class="field"><label>Tên của bạn</label><input id="f-user" value="'+esc(u.name)+'"></div><div class="field full"><label>Khuôn mặt / nhận diện</label><input id="f-face" value="'+esc(c.face)+'"></div><div class="field"><label>Tóc</label><input id="f-hair" value="'+esc(c.hair)+'"></div><div class="field"><label>Vóc dáng</label><input id="f-body" value="'+esc(c.body)+'"></div><div class="field"><label>Phong cách</label><input id="f-style" value="'+esc(c.style)+'"></div><div class="field"><label>Giọng nói</label><input id="f-voice" value="'+esc(c.voice)+'"></div><div class="field full"><label>Tính cách</label><textarea id="f-personality">'+esc(c.personality)+'</textarea></div><div class="field full"><label>Cách nói chuyện</label><textarea id="f-speech">'+esc(c.speech)+'</textarea></div><div class="field"><label>Bạn thích</label><input id="f-likes" value="'+esc(u.likes)+'"></div><div class="field"><label>Bạn không thích</label><input id="f-dislikes" value="'+esc(u.dislikes)+'"></div></div><div class="actions"><button onclick="closeModal()">Hủy</button><button class="primary" onclick="saveSetup()">Lưu nhân vật</button></div></div></div>');document.getElementById("f-rel").value=c.relationship}
function saveSetup(){const g=id=>document.getElementById(id).value;state.character={...state.character,name:g("f-name").trim()||"Linh",age:Math.max(18,+g("f-age")||25),relationship:g("f-rel"),face:g("f-face"),hair:g("f-hair"),body:g("f-body"),style:g("f-style"),voice:g("f-voice"),personality:g("f-personality"),speech:g("f-speech")};state.user={name:g("f-user"),likes:g("f-likes"),dislikes:g("f-dislikes")};state.setup=true;save();closeModal();render()}
function addMemory(text,type,importance){if(!text.trim())return;const found=state.memories.find(m=>m.text.toLowerCase()===text.toLowerCase());if(!found){state.memories.unshift({id:Date.now(),text:text.trim(),type:type||"conversation",importance:importance||1,created:new Date().toISOString()});state.memories=state.memories.slice(0,200)}}
function syncSocial(){socialFallback();state.social.lastSync=Date.now();save();render()}
function openSocial(){socialFallback();document.body.insertAdjacentHTML('beforeend','<div class="modal" id="modal"><div class="card"><h2>🌐 Đời sống mạng xã hội</h2><p class="muted">Trend sẽ được đưa vào bối cảnh nhân vật khi có nguồn dữ liệu hợp lệ.</p>'+((state.social.trends||[]).map(t=>'<div class="memory"><b>'+esc(t.title)+'</b><span>'+esc(t.summary)+'</span><small class="muted">'+esc(t.source)+'</small></div>').join(''))+'<div class="actions"><button onclick="closeModal()">Đóng</button></div></div></div>')}
function maybeProactive(){const now=Date.now();if(now-state.social.lastProactive<3600000)return null;const t=state.social.trends&&state.social.trends[0];if(!t)return null;state.social.lastProactive=now;save();return 'Em vừa thấy '+t.title.toLowerCase()+' và tự nhiên muốn kể anh nghe 😌. '+t.summary}
function extractMemory(text){const rules=[[/tôi tên là (.+)/i,"Tên của bạn là $1","profile"],[/anh tên là (.+)/i,"Tên của bạn là $1","profile"],[/tôi thích (.+)/i,"Bạn thích $1","preference"],[/anh thích (.+)/i,"Bạn thích $1","preference"],[/tôi không thích (.+)/i,"Bạn không thích $1","preference"],[/anh không thích (.+)/i,"Bạn không thích $1","preference"],[/sinh nhật (?:của )?tôi là (.+)/i,"Sinh nhật của bạn là $1","important"],[/sinh nhật (?:của )?anh là (.+)/i,"Sinh nhật của bạn là $1","important"],[/anh đang (.+)/i,"Gần đây bạn đang $1","episode"],[/tôi đang (.+)/i,"Gần đây bạn đang $1","episode"]];rules.forEach(r=>{const m=text.match(r[0]);if(m)addMemory(r[1].replace("$1",m[1]),r[2],r[2]==="important"?3:2)})}
function context(){return state.memories.slice(0,10).map(m=>m.text).join("; ")}
function response(text){const low=text.toLowerCase();let answer,action;if(/buồn|mệt|áp lực|chán|stress/.test(low)){answer="Lại đây nào. Em nghe anh kể nhé. Hôm nay có chuyện gì làm anh mệt vậy?";action="*Cô nhìn anh dịu dàng, rồi ngồi lại gần như muốn dành cho anh một khoảng yên tĩnh.*"}else if(/nhớ em|nhớ cô|nhớ/.test(low)){answer="Em cũng vui vì anh tìm đến em. Kể em nghe hôm nay của anh đi.";action="*Cô mỉm cười, ánh mắt mềm lại.*"}else if(/yêu|thương/.test(low)){answer=state.character.relationship==="wife"?"Em biết mà. Lại đây, để em ôm anh một chút.":"Nghe anh nói vậy tự nhiên em thấy vui. Em ở đây mà.";action="*Cô khẽ cười, hơi nghiêng đầu nhìn anh.*"}else{answer="Em nghe đây. "+(context()?"Em vẫn nhớ: "+context()+". ":"")+"Anh kể tiếp cho em nhé.";action="*Cô nhìn anh chăm chú, chờ anh nói tiếp.*"}return{answer,action}}
async function send(e){e.preventDefault();const input=document.getElementById("input"),text=input.value.trim();if(!text)return;state.messages.push({role:"user",text,time:Date.now()});extractMemory(text);updateCharacterState(text);socialFallback();input.value="";save();render();const api="";if(api){try{const r=await fetch(api+"/api/chat",{method:"POST",headers:{"Content-Type":"application/json","X-Session-Id":getSessionId()},body:JSON.stringify({session_id:getSessionId(),message:text,character:state.character,relationship:{stage:state.character.relationship,intimacy:state.intimacy},emotion_state:state.emotion,social_context:(state.social.trends||[]).slice(0,5),social_memory:(state.social.memories||[]).slice(0,10),personal_interests:state.social.interests})});const d=await r.json();if(!r.ok)throw new Error(d.error||"API error");state.messages.push({role:"ai",text:d.reply,action:"*Cô nhìn anh dịu dàng, giữ đúng tính cách và mối quan hệ của hai người.*",time:Date.now()});if(Array.isArray(d.memories))state.memories=d.memories.map(m=>({id:m.id,text:m.memory_key+": "+m.value,type:m.type,importance:m.importance,created:m.updated_at}));save();render()}catch(err){state.messages.push({role:"ai",text:"Em đang gặp lỗi kết nối AI. Kiểm tra API trong phần cấu hình nhé.",action:"*Cô khẽ mỉm cười và chờ anh kiểm tra kết nối.*",time:Date.now()});save();render()}}else{const r=response(text),p=maybeProactive();state.messages.push({role:"ai",text:p||r.answer,action:p?'*Cô chủ động gửi anh một điều vừa bắt gặp trong đời sống mạng xã hội.*':r.action,time:Date.now()});save();render()}}
function getSessionId(){const k="nguoi-yeu-ai-session";let x=localStorage.getItem(k);if(!x){x=crypto.randomUUID();localStorage.setItem(k,x)}return x}
function openMemories(){document.body.insertAdjacentHTML("beforeend",'<div class="modal" id="modal"><div class="card"><h2>🧠 Ký ức của em</h2><p class="muted">Thông tin được nhận diện từ cuộc trò chuyện.</p>'+(state.memories.length?state.memories.map(m=>'<div class="memory"><b>'+esc(m.text)+'</b><span class="muted">'+esc(m.type)+" · "+new Date(m.created).toLocaleDateString("vi-VN")+'</span><button style="float:right" onclick="delMemory('+m.id+')">Xóa</button></div>').join(""):'<p class="muted">Chưa có ký ức nào.</p>')+'<div class="actions"><button onclick="closeModal()">Đóng</button></div></div></div>')}
function delMemory(id){state.memories=state.memories.filter(m=>m.id!==id);save();closeModal();openMemories()}
function resetAll(){if(confirm("Xóa toàn bộ nhân vật, ký ức và hội thoại trên thiết bị này?")){localStorage.removeItem(KEY);state=load();render()}}
render();
function speakAI(text){if(!("speechSynthesis" in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text||""));u.lang="vi-VN";u.rate=.96;u.pitch=1.04;const vs=speechSynthesis.getVoices();const v=vs.find(x=>(x.lang||"").toLowerCase().startsWith("vi"));if(v)u.voice=v;speechSynthesis.speak(u)}
