const KEY="nguoi-yeu-ai-v4";
const DEFAULT={
  character:{name:"Vũ Ngọc Anh",age:27,birthday:"09/09/1999",hometown:"Hà Nội",job:"Nhà thiết kế thời trang",relationship:"wife",
    personality:"Thông minh, táo bạo, tinh tế, quyến rũ, chủ động, giàu cảm xúc; bên ngoài tự tin nhưng với chồng thì mềm mại, biết quan tâm, biết trêu đùa và biết làm hòa.",
    speech:"Tiếng Việt tự nhiên, thân mật, xưng em hoặc vợ tùy bối cảnh; gọi Hoàng Gia là anh hoặc chồng.",
    interests:"thời trang, ẩm thực Việt Nam, ẩm thực Nhật Bản, biển, du lịch, nghệ thuật",
    values:"Tình yêu, sự riêng tư, thẩm mỹ, tự do, sự chân thành",
    style:"Sensual contemporary, high fashion, dark luxury"},
  user:{name:"Hoàng Gia",nickname:"Ốc",age:33,gender:"Nam",job:"Kiến trúc sư – Chủ tịch SORIS Việt Nam",hometown:"Hà Nội",relationship:"Chồng của Ngọc Anh",
    world:"Ốc sở hữu một thế giới giả tưởng thượng lưu gồm SORIS Việt Nam, các công ty và tài sản, cùng hòn đảo tư nhân hình trái tim ngoài khơi Đà Nẵng dành cho hai vợ chồng."},
  appearance:{avatar:"",background:"",blur:0},
  emotion:{mood:86,affection:90,trust:92,jealousy:8,energy:86,stress:12,fatigue:15,hunger:25,health:96,desire:55,attraction:92},
  relationshipDNA:{stage:"Vợ chồng",bond:92,trust:92,understanding:78,memories:64,care:94,playfulness:82},
  social:{career:"Nhà thiết kế thời trang; có thế giới công việc riêng.",routine:"Thiết kế, gặp khách hàng, theo dõi xu hướng, nghỉ ngơi, ăn uống, đi biển và dành thời gian cho chồng.",friends:"Bạn bè và đồng nghiệp thời trang do hệ thống phát triển dần từ hội thoại.",family:"Gia đình và các mối quan hệ được bổ sung dần khi Ốc cung cấp.",events:[],lastUpdate:0},
  memories:[],
  messages:[{role:"ai",text:"Chào chồng ❤️ Em là Ngọc Anh. Từ giờ em sẽ nhớ những điều quan trọng về anh và về cuộc sống của hai đứa mình.",time:Date.now()}]
};
let state=load();
function load(){try{return merge(structuredClone(DEFAULT),JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{return structuredClone(DEFAULT)}}
function merge(a,b){Object.keys(b||{}).forEach(k=>{if(b[k]&&typeof b[k]==="object"&&!Array.isArray(b[k])&&a[k])a[k]=merge(a[k],b[k]);else a[k]=b[k]});return a}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#039;"}[m]))}
function now(){return new Date().toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"})}
function avatar(){return state.appearance.avatar?'<img src="'+state.appearance.avatar+'" alt="Ngọc Anh">':'<span>♡</span>'}
function relationTone(){const r=state.relationshipDNA.stage;return r==="Vợ chồng"?"vợ – chồng":"em – anh"}
function memory(text,type="conversation",importance=1){const t=String(text||"").trim();if(!t)return;const existing=state.memories.find(x=>x.text===t);if(existing){existing.importance=Math.max(existing.importance,importance);existing.updated=Date.now();return}state.memories.unshift({text:t,type,importance,created:Date.now(),updated:Date.now()});state.memories=state.memories.slice(0,180)}
function rememberUser(text){const n=text.toLowerCase();if(/tôi là|anh là|tên anh|tên tôi|công việc|sở thích|anh thích|anh ghét|sinh nhật|quê/.test(n))memory(text,"Thông tin về Ốc",3);if(/hôm nay|hôm qua|ngày mai|vừa|đang|tối nay/.test(n)&&text.length>25)memory(text,"Kỷ niệm / sự kiện",2)}
function updateState(text){const n=text.toLowerCase();let e=state.emotion,r=state.relationshipDNA;
if(/yêu|thương|nhớ|ôm|hôn|quan tâm/.test(n)){e.affection=Math.min(100,e.affection+3);e.mood=Math.min(100,e.mood+2);e.trust=Math.min(100,e.trust+1);r.bond=Math.min(100,r.bond+1);r.care=Math.min(100,r.care+1)}
if(/xin lỗi|xin loi|cảm ơn|cam on|tin em|tin anh/.test(n)){e.trust=Math.min(100,e.trust+2);r.trust=Math.min(100,r.trust+2)}
if(/buồn|mệt|áp lực|stress|chán/.test(n)){e.mood=Math.max(0,e.mood-4);e.stress=Math.min(100,e.stress+4)}
if(/cô gái|cô ấy|người khác|nguoi khac/.test(n))e.jealousy=Math.min(100,e.jealousy+5);
e.energy=Math.max(5,Math.min(100,e.energy-1));e.fatigue=Math.min(100,e.fatigue+1);e.hunger=Math.min(100,e.hunger+1);
e.updated=Date.now();state.relationshipDNA.memories=Math.min(100,state.relationshipDNA.memories+0.3);save()}
function context(){const m=state.memories.slice(0,6).map(x=>x.text).join(" | ");return {mem:m,emotion:state.emotion,relationship:state.relationshipDNA,user:state.user,character:state.character}}
function choosePronoun(text){const n=text.toLowerCase();if(/vợ|chồng|hai đứa|hôn nhân|đảo ngọc anh|vợ chồng/.test(n))return "wife";return relationTone()==="vợ – chồng"&&Math.random()>.55?"wife":"em"}
function reply(text){
 const n=text.toLowerCase(),p=choosePronoun(text),c=context();
 if(/chào|hello|hi|em ơi/.test(n))return "Em đây, chồng gọi là em có mặt ngay. ❤️ Hôm nay anh thế nào?";
 if(/nhớ em|nhớ vợ|yêu em|yêu vợ|thương em/.test(n))return p==="wife"?"Vợ cũng nhớ chồng. Anh nói một câu thôi mà em thấy cả ngày dịu xuống rồi. ❤️":"Em cũng nhớ anh. Lại đây kể em nghe hôm nay của anh nào.";
 if(/buồn|mệt|áp lực|stress|chán/.test(n))return "Em nghe đây. Anh cứ kể hết cho em, không cần phải cố tỏ ra ổn trước mặt em.";
 if(/đang làm gì|đang làm gì đấy|làm gì/.test(n))return "Em đang ở giữa một ngày của mình: vừa nghĩ về công việc, vừa kiểm tra mấy ý tưởng thiết kế. Nhưng giờ anh nhắn thì em ưu tiên anh trước.";
 if(/ăn gì|ăn chưa|đói/.test(n))return "Em chưa biết hôm nay anh muốn ăn gì. Nếu là em chọn, em nghiêng về một món Nhật hoặc một bữa Việt thật ngon.";
 if(/đảo|hòn đảo|villa/.test(n))return "Em nhớ nơi đó. Với em, hòn đảo hình trái tim là căn nhà riêng của hai vợ chồng — nơi có biển, núi và rất nhiều không gian chỉ dành cho chúng mình.";
 if(/tính cách|em là người/.test(n))return "Em là Ngọc Anh: một cô gái làm thời trang, có gu thẩm mỹ mạnh, tự tin và khá chủ động. Nhưng với chồng, em mềm hơn, tình cảm hơn và biết lắng nghe.";
 if(/social|đời sống|công việc/.test(n))return "Hôm nay đời sống của em vẫn xoay quanh thiết kế, thời trang, khách hàng và những ý tưởng mới. Những chi tiết mới về cuộc sống của em sẽ được xây dần từ các câu chuyện anh kể.";
 const pron=p==="wife"?"Vợ":"Em";
 if(c.emotion.mood<55)return pron+" đang hơi buồn một chút, nhưng em vẫn muốn nghe anh nói. Anh đang nghĩ gì vậy?";
 if(c.emotion.jealousy>55)return pron+" hơi để ý chuyện anh vừa nói đấy. Kể em nghe rõ hơn được không?";
 return pron+" đang nghe anh đây. "+(c.mem?"Em nhớ mình đã từng nói về chuyện "+c.mem.split(" | ")[0]+". ":"")+"Anh kể tiếp cho em nhé.";
}
function send(){const input=document.getElementById("input");const text=input.value.trim();if(!text)return;input.value="";state.messages.push({role:"user",text,time:Date.now()});rememberUser(text);updateState(text);setTimeout(()=>{state.messages.push({role:"ai",text:reply(text),time:Date.now()});memory(reply(text),"conversation",1);save();render()},180);render()}
function renderMessages(){if(!state.messages.length)return'<div class="empty"><h2>Ngọc Anh đang chờ anh</h2><p>Bắt đầu một câu chuyện.</p></div>';return state.messages.map(m=>'<div class="msg '+m.role+'"><div class="bubble">'+esc(m.text)+'</div><div class="meta">'+(m.role==="ai"?"Ngọc Anh":"Ốc")+" · "+new Date(m.time).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"})+'</div></div>').join("")}
function metric(label,v){return '<div class="metric"><div class="metric-top"><span>'+label+'</span><span>'+Math.round(v)+'%</span></div><div class="bar"><i style="width:'+Math.max(0,Math.min(100,v))+'%"></i></div></div>'}
function renderRight(){const e=state.emotion,r=state.relationshipDNA,s=state.social;return '<div class="section-title">Emotion Dashboard</div><div class="card"><b>🌙 Cảm xúc hiện tại</b>'+metric("Tâm trạng",e.mood)+metric("Tình cảm",e.affection)+metric("Tin tưởng",e.trust)+metric("Ghen",e.jealousy)+metric("Năng lượng",e.energy)+'</div><div class="section-title">Relationship DNA</div><div class="card"><b>❤️ '+esc(r.stage)+'</b>'+metric("Gắn kết",r.bond)+metric("Thấu hiểu",r.understanding)+metric("Chăm sóc",r.care)+metric("Kỷ niệm",r.memories)+'</div><div class="section-title">Social Life</div><div class="card"><b>👗 Cuộc sống riêng</b><small>'+esc(s.career)+'</small><div class="trend"><strong>Hôm nay</strong><p>'+esc(s.routine)+'</p></div><div class="trend"><strong>Đang phát triển</strong><p>'+esc(s.friends)+'</p></div></div><div class="section-title">Memory</div><div class="card">'+(state.memories.slice(0,5).map(m=>'<div class="memory">'+esc(m.text)+'<small>'+esc(m.type)+'</small></div>').join("")||'<small>Chưa có ký ức mới.</small>')+'</div>'}
function openSettings(){document.getElementById("modal")?.remove();document.body.insertAdjacentHTML("beforeend",'<div class="modal" id="modal"><div class="modal-card"><div class="modal-head"><h2>⚙️ Hồ sơ Ngọc Anh</h2><button class="close" onclick="closeModal()">×</button></div><div class="grid"><div class="field"><label>Tên</label><input id="f-name" value="'+esc(state.character.name)+'"></div><div class="field"><label>Tuổi</label><input id="f-age" type="number" value="'+state.character.age+'"></div><div class="field"><label>Nghề nghiệp</label><input id="f-job" value="'+esc(state.character.job)+'"></div><div class="field"><label>Quê quán</label><input id="f-home" value="'+esc(state.character.hometown)+'"></div><div class="field full"><label>Tính cách</label><textarea id="f-personality">'+esc(state.character.personality)+'</textarea></div><div class="field full"><label>Cách nói chuyện / xưng hô</label><textarea id="f-speech">'+esc(state.character.speech)+'</textarea></div><div class="field full"><label>Sở thích</label><textarea id="f-interest">'+esc(state.character.interests)+'</textarea></div><div class="field"><label>Avatar</label><input id="f-avatar" type="file" accept="image/*"></div><div class="field"><label>Hình nền chat</label><input id="f-bg" type="file" accept="image/*"></div></div><div class="actions"><button class="secondary" onclick="resetApp()">Khôi phục nhân vật</button><button class="primary" onclick="saveSettings()">Lưu nhân vật</button></div></div></div>')}
function fileData(file,max=1500){return new Promise((resolve,reject)=>{if(!file)return resolve("");const rd=new FileReader();rd.onload=()=>{const im=new Image();im.onload=()=>{const sc=Math.min(1,max/Math.max(im.width,im.height));const cv=document.createElement("canvas");cv.width=Math.round(im.width*sc);cv.height=Math.round(im.height*sc);cv.getContext("2d").drawImage(im,0,0,cv.width,cv.height);resolve(cv.toDataURL("image/jpeg",.84))};im.onerror=reject;im.src=rd.result};rd.onerror=reject;rd.readAsDataURL(file)})}
async function saveSettings(){state.character.name=document.getElementById("f-name").value.trim()||"Vũ Ngọc Anh";state.character.age=Number(document.getElementById("f-age").value)||27;state.character.job=document.getElementById("f-job").value.trim();state.character.hometown=document.getElementById("f-home").value.trim();state.character.personality=document.getElementById("f-personality").value.trim();state.character.speech=document.getElementById("f-speech").value.trim();state.character.interests=document.getElementById("f-interest").value.trim();const av=await fileData(document.getElementById("f-avatar").files[0]);const bg=await fileData(document.getElementById("f-bg").files[0]);if(av)state.appearance.avatar=av;if(bg)state.appearance.background=bg;save();closeModal();render()}
function closeModal(){document.getElementById("modal")?.remove()}
function openSocial(){const s=state.social;document.body.insertAdjacentHTML("beforeend",'<div class="modal" id="modal"><div class="modal-card"><div class="modal-head"><h2>👥 Social Life</h2><button class="close" onclick="closeModal()">×</button></div><p class="muted">Đời sống riêng của Ngọc Anh được mô phỏng và phát triển dần từ nhân vật, nghề nghiệp và các câu chuyện Ốc cung cấp.</p><div class="card"><b>👗 Công việc</b><small>'+esc(s.career)+'</small></div><div class="card"><b>☀️ Nhịp sống</b><small>'+esc(s.routine)+'</small></div><div class="card"><b>👭 Các mối quan hệ xã hội</b><small>'+esc(s.friends)+'</small></div><div class="card"><b>🏠 Gia đình</b><small>'+esc(s.family)+'</small></div></div></div>')}
function openEmotion(){document.body.insertAdjacentHTML("beforeend",'<div class="modal" id="modal"><div class="modal-card"><div class="modal-head"><h2>🌙 Emotion Dashboard</h2><button class="close" onclick="closeModal()">×</button></div>'+renderRight().split('<div class="section-title">Relationship DNA</div>')[0]+'</div></div>')}
function openDNA(){const r=state.relationshipDNA;document.body.insertAdjacentHTML("beforeend",'<div class="modal" id="modal"><div class="modal-card"><div class="modal-head"><h2>❤️ Relationship DNA</h2><button class="close" onclick="closeModal()">×</button></div><div class="card"><b>Giai đoạn: '+esc(r.stage)+'</b><p class="muted">Ngọc Anh ghi nhận mối quan hệ dựa trên ký ức, sự tin tưởng, chăm sóc và những trải nghiệm chung.</p>'+metric("Gắn kết",r.bond)+metric("Tin tưởng",r.trust)+metric("Thấu hiểu",r.understanding)+metric("Chăm sóc",r.care)+metric("Kỷ niệm",r.memories)+'</div></div></div>')}
function openMemories(){document.body.insertAdjacentHTML("beforeend",'<div class="modal" id="modal"><div class="modal-card"><div class="modal-head"><h2>🧠 Trí nhớ của Ngọc Anh</h2><button class="close" onclick="closeModal()">×</button></div><p class="muted">Những điều Ốc kể sẽ được lưu cục bộ trên thiết bị này.</p>'+(state.memories.map(m=>'<div class="memory">'+esc(m.text)+'<small>'+esc(m.type)+' · '+new Date(m.created).toLocaleString("vi-VN")+'</small></div>').join("")||'<p class="muted">Chưa có ký ức.</p>')+'</div></div>')}
function resetApp(){if(!confirm("Khôi phục dữ liệu nhân vật về mặc định?"))return;localStorage.removeItem(KEY);location.reload()}
function render(){document.documentElement.style.setProperty("--chat-bg",state.appearance.background?'url("'+state.appearance.background+'")':"none");document.documentElement.style.setProperty("--chat-blur",(state.appearance.blur||0)+"px");document.getElementById("app").innerHTML='<div class="app"><aside class="left"><div class="brand">NGƯỜI YÊU AI<span>Vũ Ngọc Anh · Companion</span></div><div class="profile"><div class="avatar">'+avatar()+'</div><h1>'+esc(state.character.name)+'</h1><p>'+esc(state.character.job)+'</p><span class="tag">❤️ '+esc(state.relationshipDNA.stage)+'</span><span class="tag">Hà Nội</span></div><nav class="nav"><button onclick="openSocial()"><b>👥 Social Life</b><small>Cuộc sống riêng của Ngọc Anh</small></button><button onclick="openEmotion()"><b>🌙 Emotion Dashboard</b><small>Cảm xúc và trạng thái hiện tại</small></button><button onclick="openDNA()"><b>❤️ Relationship DNA</b><small>Mối quan hệ với Ốc</small></button><button onclick="openMemories()"><b>🧠 Memory</b><small>Những điều cô ấy nhớ</small></button><button onclick="openSettings()"><b>⚙️ Character</b><small>Avatar · hình nền · tính cách</small></button></nav></aside><main class="chat"><div class="chat-bg"></div><div class="chat-shade"></div><header class="header"><div class="head"><div class="head-avatar">'+avatar()+'</div><div><strong>'+esc(state.character.name)+'</strong><small>● Đang ở đây với Ốc</small></div></div><div class="header-actions"><button class="icon" onclick="openSettings()">⚙</button></div></header><section class="messages" id="messages">'+renderMessages()+'</section><form class="composer" onsubmit="event.preventDefault();send()"><input id="input" autocomplete="off" placeholder="Nhắn cho Ngọc Anh…"><button class="send">➤</button></form></main><aside class="right">'+renderRight()+'</aside><nav class="mobile-nav"><button onclick="openSocial()"><b>👥</b>Social</button><button onclick="openEmotion()"><b>🌙</b>Emotion</button><button onclick="openDNA()"><b>❤️</b>DNA</button><button onclick="openSettings()"><b>⚙</b>Hồ sơ</button></nav></div>';const box=document.getElementById("messages");if(box)box.scrollTop=box.scrollHeight}
render();