const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type, X-Session-Id","Access-Control-Allow-Methods":"GET, POST, DELETE, OPTIONS"};
const out=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"Content-Type":"application/json; charset=utf-8",...CORS}});
const uid=()=>crypto.randomUUID();
function prompt(c,r,m){return ["You are a fictional adult AI companion (18+), one fixed character only.","Never claim to be a real human. emotion_state is simulated.","Keep Character DNA and Relationship DNA consistent. Never invent memories.","Reply naturally in Vietnamese. Use roleplay with dialogue plus a short action/expression.","If new information conflicts with memory, prefer the new information.","Do not generate graphic sexual content.","CHARACTER:",JSON.stringify(c),"RELATIONSHIP:",JSON.stringify(r),"MEMORIES:",JSON.stringify(m),"EMOTION:",JSON.stringify(arguments[3]||{}),"SOCIAL:",JSON.stringify(arguments[4]||[])].join("\n")}
async function ai(env,messages){const x=await env.AI.run("@cf/zai-org/glm-4.7-flash",{messages,max_tokens:500,temperature:0.85});return x?.response||x?.result?.response||""}
async function memories(env,s){const x=await env.DB.prepare("SELECT id,type,memory_key,value,importance,updated_at FROM memories WHERE session_id=? ORDER BY importance DESC,updated_at DESC LIMIT 30").bind(s).all();return x.results||[]}
async function extract(env,u,a){try{const x=await ai(env,[{role:"system",content:"Extract only durable facts from the conversation. Return JSON array only: [{\"type\":\"profile|preference|episode|relationship|important\",\"key\":\"...\",\"value\":\"...\",\"importance\":1-5,\"action\":\"create|update|supersede|ignore\"}] Do not guess."},{role:"user",content:"USER: "+u+"\nAI: "+a}]);const q=x.match(/\[[\s\S]*\]/);return q?JSON.parse(q[0]):[]}catch(e){return[]}}
async function saveMemory(env,s,m){if(!m||m.action==="ignore"||!m.key||!m.value)return;const old=await env.DB.prepare("SELECT id FROM memories WHERE session_id=? AND memory_key=? LIMIT 1").bind(s,m.key).first();const imp=Math.max(1,Math.min(5,Number(m.importance)||2));if(old)await env.DB.prepare("UPDATE memories SET type=?,value=?,importance=?,updated_at=datetime('now') WHERE id=?").bind(m.type||"important",m.value,imp,old.id).run();else await env.DB.prepare("INSERT INTO memories(id,session_id,type,memory_key,value,importance,updated_at) VALUES(?,?,?,?,?,?,datetime('now'))").bind(uid(),s,m.type||"important",m.key,m.value,imp).run()}
async function chat(req,env){const b=await req.json();const s=req.headers.get("X-Session-Id")||b.session_id;if(!s||!b.message)return out({error:"Missing session_id or message"},400);const ms=await memories(env,s);const h=await env.DB.prepare("SELECT role,content FROM messages WHERE session_id=? ORDER BY created_at DESC LIMIT 16").bind(s).all();const recent=(h.results||[]).reverse();const reply=await ai(env,[{role:"system",content:prompt(b.character||{},b.relationship||{},ms)},...recent,{role:"user",content:b.message}]);if(!reply)return out({error:"AI returned empty response"},502);await env.DB.batch([env.DB.prepare("INSERT INTO messages(id,session_id,role,content,created_at) VALUES(?,?,?,?,datetime('now'))").bind(uid(),s,"user",b.message),env.DB.prepare("INSERT INTO messages(id,session_id,role,content,created_at) VALUES(?,?,?,?,datetime('now'))").bind(uid(),s,"assistant",reply)]);for(const m of await extract(env,b.message,reply))await saveMemory(env,s,m);return out({reply,memories:await memories(env,s),emotion_state:{mood:"neutral",energy:.7,affection:.6,shyness:.2,playfulness:.5,trust:.7}})}
export default {async fetch(req,env){if(req.method==="OPTIONS")return new Response(null,{headers:CORS});const u=new URL(req.url);try{if(u.pathname==="/api/health")return out({ok:true});if(u.pathname==="/api/chat"&&req.method==="POST")return chat(req,env);if(u.pathname==="/api/memories"&&req.method==="GET"){const s=req.headers.get("X-Session-Id");return out({memories:s?await memories(env,s):[]})}if(u.pathname==="/api/memories"&&req.method==="DELETE"){const s=req.headers.get("X-Session-Id");if(!s)return out({error:"Missing session"},400);await env.DB.prepare("DELETE FROM memories WHERE session_id=?").bind(s).run();return out({ok:true})}if(u.pathname==="/api/social/trends"&&req.method==="GET"){const x=await env.DB.prepare("SELECT id,source,title,url,category,region,language,score,published_at,fetched_at,summary,tags FROM social_trends WHERE region='VN' ORDER BY score DESC,fetched_at DESC LIMIT 30").all();return out({trends:x.results||[]})}return out({error:"Not found"},404)}catch(e){return out({error:e.message||"Server error"},500)}}};